[tools]
helm = "latest"
java = "openjdk-25.0.2"
k3d = "latest"
k9s = "latest"
kubectl = "latest"
maven = "3.9.16"
node = "lts"
trivy = "latest"
vim = "latest"

[env]
APP_REPO = 'todo-app'
GITOPS_REPO = 'k8s-gitops'

[hooks]
enter = "bash ./.devcontainer/scripts/setup_project.sh"
