apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      name: backend
      labels:
        app: backend
    spec:
      initContainers:
        - name: wait-cnpg-pod-up
          image: busybox:1.38-musl
          command:
            - sh
            - -c
            - |
              echo "Waiting for CNPG database Pod is available:"
              until nc -z -w 2 todo-database-v1-rw 5432; do
                echo "CNPG database Pod not ready..."
                sleep 5
              done
              echo "CNPG database Pod is ready."
      containers:
        - name: backend
          image: todo-backend:1.0
          imagePullPolicy: Never
          ports:
            - containerPort: 22111
              protocol: TCP

          livenessProbe:
            httpGet:
              port: 22111
              path: "/health"
            initialDelaySeconds: 10
            periodSeconds: 30
            failureThreshold: 5

          envFrom:
            - configMapRef:
                name: todo-db-config
          env:
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: todo-db-creds
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: todo-db-creds
                  key: password

      restartPolicy: Always
