apiVersion: v1
# placeholders, overwritten by the dev overlay's patch+replacements
data:
  password: cGFzc3dvcmQ=
  username: dXNlcm5hbWU=
kind: Secret
metadata:
  name: todo-db-creds
type: kubernetes.io/basic-auth
